### ISSUE TITLE
TASK LIST

### ISSUE THREAD

**Issue by fscheiner** [gridcf/gct-docs#13]
Here I try to collect needed changes for the documentation that need to be fixed but require some additional work, research, discussion etc. beforehand. Feel free to add needed changes or mark needed changes as implemented.

**Comment by fscheiner** [comment]
- [x] On [/6.2/gridftp/GridFTP_Interface_Config_Client_Firewall_Frag.adoc](https://github.com/gridcf/gct-docs/blob/0bde120ae6300d32891768bdd6c870087a00ece7/6.2/gridftp/GridFTP_Interface_Config_Client_Firewall_Frag.adoc)
there's still a link pointing back to the old Globus Toolkit site at the bottom. But the referenced documentation is no longer available, the [PDF](http://toolkit.globus.org/toolkit/security/firewalls/Globus-Firewall-Requirements-9.pdf) there is marked "historical" and from 2006. A version from 2008 is still available in the Internet Archive: https://web.archive.org/web/20140716211230/http://dev.globus.org/wiki/FirewallHowTo

**Comment by fscheiner** [comment]
* [x] On [/6.2/gridftp/GridFTP_Known_Problems_Frag.adoc](https://github.com/gridcf/gct-docs/blob/0bde120ae6300d32891768bdd6c870087a00ece7/6.2/gridftp/GridFTP_Known_Problems_Frag.adoc) the links pointing to the Globus JIRA need to be changed to point to our archived version at https://gridcf.org/gct-docs/gt-jira-archive/.

**Comment by fscheiner** [comment]
* [x] On [/6.2/gridftp/mig/index.adoc](https://github.com/gridcf/gct-docs/blob/0bde120ae6300d32891768bdd6c870087a00ece7/6.2/gridftp/mig/index.adoc) migration from GCT6.0 should also be included with "no changes needed".

**Comment by fscheiner** [comment]
-  [x]  The [globus-url-copy manpage](https://github.com/gridcf/gct-docs/blob/0bde120ae6300d32891768bdd6c870087a00ece7/6.2/gridftp/globus-url-copy-manual.adoc) needs to be updated due to https://github.com/gridcf/gct/pull/100

**Comment by fscheiner** [comment]
- [x] The ["Email Support" section in the "GRAM5: Developer’s Guide"](https://gridcf.org/gct-docs/latest/gram5/developer/index.html#_email_support) needs an update as it still refers to old Globus web pages and mailing lists.

**Comment by fscheiner** [comment]
- [x] There is - most likely - a `*` missing on [Configuring GCT to Trust a Particular Certificate Authority](https://gridcf.org/gct-docs/latest/gsic/admin/index.html#gsic-configuring-trustCA) in: 
```
Some very simple wildcard matching is done: if the Distinguished Name Pattern ends with a , then any
distinguished name that matches the part of the CA subject name before the is considered a match.
```

**Comment by fscheiner** [comment]
- [x] https://gridcf.org/gct-docs/6.2/admin/install/index.html#gtadmin-installation-from-source-installer includes the "gsi" Makefile target and description twice:
```
Installing from Source Installer
[...]
4. The source installer will build all of the Grid Community Toolkit packages in the default make rule. The following Makefile targets can be used to build subsets of the Grid Community Toolkit:
[...]
gsi

    Security Libraries and Tools
gsi

    Security Libraries and Tools
[...]
```

**Comment by fscheiner** [comment]
- [x] https://gridcf.org/gct-docs/latest/appendices/commands/index.html#grid-proxy-init includes dated information (e.g. 512 bit keys, etc.) and a typo in the first paragraph: "[...] proxy certificate. . Command-line options [...]".  
The examples below should also be reworked (~plus check the [manpage of `grid-proxy-init`](https://github.com/gridcf/gct/blob/master/gsi/proxy/proxy_utils/source/programs/grid-proxy-init.txt) for containing current information, too!~ => they contain current information!).  
The link below "Compatibility" needs to be updated as it is no longer available in the WWW, but there is [a copy from 2013 available in the Web Archive](https://web.archive.org/web/20130817025920/http://dev.globus.org/wiki/Security/ProxyCertTypes). The "Compatibility" paragraph is not part of the manpage in the GCT source.

**Comment by fscheiner** [comment]
- [x] https://github.com/gridcf/gct/pull/216 showed that our documentation for `globus-url-copy` (specifically https://github.com/gridcf/gct-docs/blob/adoc/6.2/gridftp/globus-url-copy-manual.adoc) is out of sync with [the actual source for the manual page](https://github.com/gridcf/gct/blob/master/gass/copy/source/globus-url-copy.txt). This needs to be fixed before the next release.

**Comment by fscheiner** [comment]
- [ ] https://github.com/gridcf/gct-docs/pull/32#issuecomment-1334916214 needs to be handled. My proposal is to replace the certs with _"some John Doe ones from a Jane Doe's CA or so"_ created with simpleca.

**Comment by fscheiner** [comment]
- [ ] https://gridcf.org/gct-docs/6.2/gridftp/user/index.html#globus-url-copy-interactiveclients needs an update in regard to UberFTP, which - already since a while - is maintained by the GridCF.
